export interface Iproduct {
  id: number
  title: string
  price: number
  description?: string
  image: string
  timestamp: number
}

export interface EcwidProduct {
  attributes: string[]
  autogeneratedSlug: string
  borderInfo: {
    dominatingColor: {
      alpha: number
      blue: number
      green: number
      red: number
    }
    homogeneity: boolean
  }
  categories: object[]
  categoryIds: number[]
  combinations: string[]
  createTimestamp: number
  created: string
  customSlug: string
  defaultCategoryId: number
  defaultCombinationId: number
  defaultDisplayedPrice: number
  defaultDisplayedPriceFormatted: string
  description: string
  dimensions: {
    height: number
    length: number
    width: number
  }
  discountsAllowed: boolean
  enabled: boolean
  fixedShippingRate: number
  fixedShippingRateOnly: boolean
  galleryImages: object[]
  googleItemCondition: string
  hasFreeShipping: boolean
  hdThumbnailUrl: string
  id: number
  imageUrl: string
  inStock: boolean
  isGiftCard: boolean
  isSampleProduct: boolean
  isShippingRequired: boolean
  lowestPriceSettings: {
    lowestPriceEnabled: boolean
  }
  media: object
  name: string
  nameYourPriceEnabled: boolean
  options: object[]
  originalImage: object
  originalImageUrl: string
  price: number
  priceInProductList: number
  productClassId: number
  relatedProducts: object
  seoDescription: string
  seoTitle: string
  shipping: object
  showOnFrontpage: boolean
  sku: string
  smallThumbnailUrl: string
  tax: object
  thumbnailUrl: string
  unlimited: boolean
  updateTimestamp: number
  updated: string
  url: string
  volume: number
}
